
-- 1) Add new columns
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS order_index integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS arabic_title text,
  ADD COLUMN IF NOT EXISTS dm_price_eur numeric,
  ADD COLUMN IF NOT EXISTS sub_category text,
  ADD COLUMN IF NOT EXISTS key_benefits text[],
  ADD COLUMN IF NOT EXISTS suitable_for text,
  ADD COLUMN IF NOT EXISTS how_to_use text,
  ADD COLUMN IF NOT EXISTS key_ingredients text[],
  ADD COLUMN IF NOT EXISTS product_details text,
  ADD COLUMN IF NOT EXISTS warnings text,
  ADD COLUMN IF NOT EXISTS source_url text;

CREATE INDEX IF NOT EXISTS idx_products_order_index ON public.products (order_index);

-- 2) Wipe existing data
DELETE FROM public.reviews;
DELETE FROM public.products;

-- 3) Ensure categories
INSERT INTO public.categories (slug, name, name_en, sort_order)
VALUES
  ('hair-care', 'العناية بالشعر', 'Hair Care', 1),
  ('skincare', 'العناية بالبشرة', 'Skincare', 2)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, name_en = EXCLUDED.name_en, sort_order = EXCLUDED.sort_order;

-- 4) Insert 19 products
WITH cats AS (
  SELECT slug, id FROM public.categories WHERE slug IN ('hair-care','skincare')
)
INSERT INTO public.products
  (order_index, name, name_en, arabic_title, slug, brand, category_id, sub_category,
   price, dm_price_eur, stock, images, short_description, key_benefits, suitable_for,
   how_to_use, key_ingredients, product_details, warnings, is_active)
VALUES
(1, 'LANGHAARMÄDCHEN Kopfhautpflege Tonic Lovely Long, 75 ml', 'LANGHAARMÄDCHEN Kopfhautpflege Tonic Lovely Long, 75 ml',
 'تونك فروة الرأس Lovely Long من Langhaar Mädchen', 'langhaar-maedchen-scalp-booster-tonic-lovely-long',
 'Langhaar Mädchen', (SELECT id FROM cats WHERE slug='hair-care'), 'Scalp Care',
 935, 4.95, 0, '[]'::jsonb,
 'تونك خفيف لفروة الرأس يساعد على دعم نمو الشعر وتحسين مظهر الكثافة مع الاستخدام المنتظم.',
 ARRAY['يساعد على تحسين نمو الشعر','يدعم مظهر شعر أكثر كثافة خلال 3 أشهر','يحتوي على AnaGain ومستخلص زهر اللوز','بدون سيليكون','Vegan'],
 'مناسب للشعر العادي وفروة الرأس التي تحتاج إلى دعم يومي للنمو والكثافة.',
 'يُستخدم مرتين يوميًا صباحًا ومساءً على فروة رأس جافة أو رطبة. يُوزّع بالتساوي ثم يُدلّك بلطف. لا يُشطف.',
 ARRAY['AnaGain / Pisum Sativum Sprout Extract','Caffeine','Panthenol','Glycerin','Almond blossom extract'],
 'حجم 75 ml. منتج مخصص لفروة الرأس. Vegan، بدون سيليكون وبدون Sulfate.',
 'للاستخدام الخارجي فقط. تجنب ملامسة العينين. أوقف الاستخدام عند حدوث تهيج.', true),

(2, 'Balea Professional Over Night Fluid Keratin Repair, 100 ml', 'Balea Professional Over Night Fluid Keratin Repair, 100 ml',
 'كريم/فلويد ليلي Keratin Repair من Balea Professional', 'balea-professional-keratin-repair-over-night-fluid',
 'Balea Professional', (SELECT id FROM cats WHERE slug='hair-care'), 'Night Hair Treatment',
 520, 2.75, 0, '[]'::jsonb,
 'عناية ليلية للشعر المتضرر تساعد على تقليل مظهر التقصف وتحسين ملمس الأطراف أثناء النوم.',
 ARRAY['يحمي الشعر من الاحتكاك أثناء النوم','يساعد على تقليل مظهر التقصف والتكسر','يحتوي على Keratin وPeptides','بدون سيليكون','مناسب للشعر المتضرر والضعيف'],
 'مناسب للشعر المتضرر، المتقصف، والضعيف بنيويًا.',
 'قبل النوم، ضعي 2–3 ضغطات على اليدين ثم وزعيها على أطوال وأطراف الشعر. لا يُشطف. في الصباح صففي الشعر كالمعتاد.',
 ARRAY['Hydrolyzed Keratin','Hydrolyzed Wheat Protein','Hydrolyzed Corn Protein','Hydrolyzed Soy Protein','Panthenol','Glycerin'],
 'حجم 100 ml. عناية ليلية للشعر. بدون سيليكون وبدون Sulfate.',
 'للاستخدام الخارجي فقط. تجنب فروة الرأس الحساسة إذا حدث تهيج.', true),

(3, 'Balea Professional Plex Care 2in1 Haarmaske, 250 ml', 'Balea Professional Plex Care 2in1 Haarmaske, 250 ml',
 'ماسك شعر Plex Care 2 in 1 من Balea Professional', 'balea-professional-plex-care-2in1-hair-mask',
 'Balea Professional', (SELECT id FROM cats WHERE slug='hair-care'), 'Hair Mask',
 520, 2.75, 0, '[]'::jsonb,
 'ماسك عميق للشعر المعالج كيميائيًا والمتضرر، يمكن استخدامه كـ Pre-Wash أو كـ Hair Mask بعد الشامبو.',
 ARRAY['يساعد على ملء الفجوات في بنية الشعر المتضرر','للشعر المعالج كيميائيًا والمتضرر','مع 3-Fach Protein-Komplex وAminosäuren','يمكن استخدامه قبل الغسيل أو بعد الشامبو','يساعد على نعومة ولمعان الشعر'],
 'مناسب للشعر المصبوغ، المعالج كيميائيًا، والمتضرر من الحرارة أو التقصف.',
 'كقناع بعد الشامبو: يوضع على الشعر المبلل لمدة حوالي 3 دقائق ثم يُشطف جيدًا. كـ Pre-Wash: يوضع على شعر مجفف بالمنشفة لمدة 10 دقائق على الأقل ثم يُغسل بالشامبو والبلسم.',
 ARRAY['Amino acids','3-Fach Protein-Komplex','Hydrolyzed Keratin','Panthenol','Hydrolyzed Pea Protein','Hydrolyzed Silk'],
 'حجم 250 ml. 2in1 Haarmaske + Pre-Wash-Kur. مخصص للشعر المتضرر والمعالج كيميائيًا.',
 'يُشطف جيدًا. تجنب ملامسة العينين.', true),

(4, 'Balea Professional Conditioner Plex Care, 200 ml', 'Balea Professional Conditioner Plex Care, 200 ml',
 'بلسم Plex Care من Balea Professional', 'balea-professional-plex-care-conditioner',
 'Balea Professional', (SELECT id FROM cats WHERE slug='hair-care'), 'Conditioner',
 370, 1.95, 0, '[]'::jsonb,
 'بلسم للشعر المتضرر يساعد على تحسين سهولة التمشيط واللمعان وتقوية مظهر ألياف الشعر.',
 ARRAY['يحسن سهولة التمشيط','يساعد على لمعان الشعر','يدعم الشعر المعالج كيميائيًا','مع Aminosäuren و3-Fach Protein-Komplex','يساعد على تنعيم سطح الشعر'],
 'مناسب للشعر المتضرر والمعالج كيميائيًا.',
 'يدلك بلطف على الشعر المبلل بعد الشامبو، يُترك لفترة قصيرة، ثم يُشطف جيدًا بالماء الفاتر.',
 ARRAY['Hydrolyzed Keratin','Amino acids','Panthenol','Hydrolyzed Pea Protein','Ricinus Communis Seed Oil'],
 'حجم 200 ml. Conditioner مخصص للشعر المتضرر.',
 'تجنب ملامسة العينين. في حالة ملامسة العينين يُشطف بالماء جيدًا.', true),

(5, 'Schaebens Vitamin C Gel Maske, 2x5 ml', 'Schaebens Vitamin C Gel Maske, 2x5 ml',
 'ماسك جل Vitamin C من Schaebens', 'schaebens-vitamin-c-gel-maske',
 'Schaebens', (SELECT id FROM cats WHERE slug='skincare'), 'Face Mask',
 115, 0.60, 0, '[]'::jsonb,
 'ماسك جل بفيتامين C وNiacinamide يمنح البشرة إحساسًا بالترطيب والنضارة مع Glow Effect.',
 ARRAY['يساعد على ترطيب البشرة','Glow Effect','ينعم مظهر البشرة','مع Vitamin C وNiacinamide','مناسب لكل أنواع البشرة','Vegan'],
 'مناسب لكل أنواع البشرة، خصوصًا البشرة الباهتة أو التي تحتاج إلى إشراقة.',
 'يوضع بالتساوي على بشرة نظيفة للوجه والرقبة مع تجنب منطقة العين والشفاه. يُترك حوالي 10 دقائق ثم تُزال البقايا بمنديل تجميلي. يمكن استخدامه حتى 3 مرات أسبوعيًا حسب الحاجة.',
 ARRAY['Vitamin C derivative / Sodium Ascorbyl Phosphate','Niacinamide','Panthenol','Biotin','Glycerin'],
 'حجم 2x5 ml، يكفي لاستخدامين. Gel Mask بتركيبة Vegan.',
 'للاستخدام الخارجي فقط. تجنب منطقة العين والشفاه.', true),

(6, 'Balea Professional Haaröl Plex Care, 50 ml', 'Balea Professional Haaröl Plex Care, 50 ml',
 'زيت شعر Plex Care من Balea Professional', 'balea-professional-plex-care-hair-oil',
 'Balea Professional', (SELECT id FROM cats WHERE slug='hair-care'), 'Hair Oil',
 520, 2.75, 0, '[]'::jsonb,
 'زيت شعر خفيف للشعر المتضرر والمعالج كيميائيًا، مع حماية حرارية حتى 230°C.',
 ARRAY['يدعم بنية الشعر المتضرر','يساعد على تنعيم الشعر','حماية حرارية حتى 230°C','للشعر المعالج كيميائيًا والمتضرر','Vegan'],
 'مناسب للشعر المتضرر، المصبوغ، والمعالج كيميائيًا.',
 'تُستخدم كمية صغيرة على الأطوال والأطراف حسب الحاجة، خاصة قبل التصفيف الحراري. لا يوضع بكثرة على الجذور.',
 ARRAY['Helianthus Annuus Seed Oil','Dimethiconol','Zea Mays Oil','Isododecane'],
 'حجم 50 ml. Hair oil مع Intense-Repair-Technologie وحماية حرارية.',
 'استخدم كمية قليلة فقط. تجنب ملامسة العينين.', true),

(7, 'Schaebens AHA Peeling Tuchmaske, 1 St', 'Schaebens AHA Peeling Tuchmaske, 1 St',
 'ماسك قماشي AHA Peeling من Schaebens', 'schaebens-aha-peeling-sheet-mask',
 'Schaebens', (SELECT id FROM cats WHERE slug='skincare'), 'Sheet Mask',
 275, 1.45, 0, '[]'::jsonb,
 'ماسك قماشي مقشر بأحماض AHA يساعد على تنعيم ملمس البشرة وتحسين مظهرها.',
 ARRAY['مع AHA-Fruchtsäure','مع Niacinamide وPanthenol','يساعد على إزالة الخلايا الميتة','يساعد على مظهر بشرة أنقى','مناسب لكل أنواع البشرة'],
 'مناسب لكل أنواع البشرة، مع الحذر للبشرة الحساسة جدًا بسبب التقشير.',
 'يوضع على بشرة نظيفة ويُترك 5–10 دقائق فقط، ثم يُزال الماسك وتُشطف البقايا بالماء الدافئ. يستخدم 2–3 مرات أسبوعيًا حسب تحمل البشرة.',
 ARRAY['AHA fruit acids','Glycolic Acid','Lactic Acid','Niacinamide','Panthenol','Sodium Hyaluronate'],
 'ماسك قماشي للاستخدام الواحد. يمكن حفظه في الثلاجة لانتعاش إضافي.',
 'تجنب منطقة العين والشفاه. لا يُترك أكثر من 10 دقائق. استخدم واقي شمس في اليوم التالي لأن أحماض التقشير قد تزيد حساسية البشرة للشمس.', true),

(8, 'Balea Q10 Anti-Falten Konzentrat, 7 St', 'Balea Q10 Anti-Falten Konzentrat, 7 St',
 'كبسولات Q10 Anti-Falten من Balea', 'balea-q10-anti-falten-konzentrat',
 'Balea', (SELECT id FROM cats WHERE slug='skincare'), 'Serum Capsules',
 160, 0.85, 0, '[]'::jsonb,
 'كبسولات عناية مركزة للبشرة مع Q10 وGinseng Extract لدعم مظهر بشرة أنعم وأكثر مرونة.',
 ARRAY['مع Q10 وGinseng Extract','يدعم مرونة البشرة','يساعد على مظهر بشرة أكثر نعومة','يترك إحساسًا ناعمًا على البشرة','مناسب لكل أنواع البشرة'],
 'مناسب لكل أنواع البشرة، خصوصًا البشرة التي تحتاج إلى عناية ضد علامات الإرهاق والخطوط الرفيعة.',
 'تفتح الكبسولة وتوزع محتوياتها على بشرة نظيفة، غالبًا كخطوة Serum قبل الكريم. تُستخدم حسب الحاجة أو كروتين عناية مركز.',
 ARRAY['Q10','Ginseng Extract','Vitamin E','Shambrilla Oil'],
 'عبوة تحتوي على 7 كبسولات. بدون Alcohol وبدون Parabens وبدون Farbstoffe حسب بيانات المنتج.',
 'للاستخدام الخارجي فقط. تجنب العينين.', true),

(9, 'Schaebens Totes Meer Schlamm Maske, 15 ml', 'Schaebens Totes Meer Schlamm Maske, 15 ml',
 'ماسك طين البحر الميت من Schaebens', 'schaebens-totes-meer-schlamm-maske',
 'Schaebens', (SELECT id FROM cats WHERE slug='skincare'), 'Face Mask',
 105, 0.55, 0, '[]'::jsonb,
 'ماسك طين البحر الميت للبشرة غير النقية، يساعد على التنظيف العميق وتقليل مظهر اللمعان.',
 ARRAY['مع طين البحر الميت','مع Algen وZink وMineralien','يساعد على تنظيف البشرة بعمق','يساعد على تقليل مظهر الدهون واللمعان','مناسب للبشرة غير النقية'],
 'مناسب للبشرة غير النقية والدهنية والمعرضة للحبوب والرؤوس السوداء.',
 'يُعجن الكيس قبل الفتح، ثم يوضع بالتساوي على الوجه والرقبة بعد التنظيف مع تجنب العين والشفاه. يُترك 10–15 دقيقة ثم يُغسل بالماء الدافئ. يستخدم 1–3 مرات أسبوعيًا حسب الحاجة.',
 ARRAY['Dead Sea mud / Silt','Kaolin','Zinc Oxide','Aloe Vera','Chamomile Extract','Spirulina'],
 'حجم 15 ml، لاستخدام واحد. مناسب للتنظيف المكثف للبشرة غير النقية.',
 'للاستخدام الخارجي فقط. لا يوضع على الجلد المتهيج أو المجروح.', true),

(10, 'Balea Aloe Vera Maske, 16 ml', 'Balea Aloe Vera Maske, 16 ml',
 'ماسك Aloe Vera من Balea', 'balea-aloe-vera-face-mask',
 'Balea', (SELECT id FROM cats WHERE slug='skincare'), 'Face Mask',
 85, 0.45, 0, '[]'::jsonb,
 'ماسك ترطيب بالألوفيرا وماء حراري يمنح البشرة إحساسًا بالانتعاش والراحة.',
 ARRAY['مع 70% Aloe Vera','مع Thermal Water','ترطيب مكثف وطويل الإحساس','ينعش ويهدئ البشرة','Vegan'],
 'مناسب للبشرة العادية وكل بشرة تحتاج إلى ترطيب وتهدئة.',
 'يوضع بسخاء على بشرة نظيفة مع تجنب العين والشفاه. يُترك 10–15 دقيقة، ثم تُزال البقايا بمنديل تجميلي أو تُدلك بلطف. يستخدم 1–2 مرة أسبوعيًا.',
 ARRAY['Aloe Vera','Thermal Water','Panthenol','Shea Butter','Glycerin'],
 'حجم 16 ml / 2x8 ml. Sachet يكفي لاستخدامين.',
 'للاستخدام الخارجي فقط. لا يُستخدم للأطفال.', true),

(11, 'Balea Glow Peel-Off Maske, 16 ml', 'Balea Glow Peel-Off Maske, 16 ml',
 'ماسك Glow Peel-Off من Balea', 'balea-glow-peel-off-mask',
 'Balea', (SELECT id FROM cats WHERE slug='skincare'), 'Peel-Off Mask',
 85, 0.45, 0, '[]'::jsonb,
 'ماسك Peel-Off يمنح البشرة إحساسًا بالنقاء والانتعاش مع Glow Effect.',
 ARRAY['Peel-Off Mask','مع Lotus Flower Extract','تنظيف عميق','يساعد على مظهر بشرة أكثر إشراقًا','Vegan'],
 'مناسب للوجه، خصوصًا عند الحاجة إلى تنظيف وانتعاش ومظهر Glow.',
 'يوضع على بشرة نظيفة مع تجنب العين والحواجب وخط الشعر والشفاه. يُترك حتى يجف ثم يُسحب بلطف. تُزال البقايا بالماء الفاتر.',
 ARRAY['Lotus Flower Extract','Shimmer particles','Film-forming peel-off base'],
 'حجم 16 ml / 2x8 ml. pH-hautneutral وVegan حسب بيانات المنتج.',
 'لا يستخدم حول العينين أو على البشرة المتهيجة. لا يُنزع بعنف.', true),

(12, 'Balea Milch & Honig Maske, 16 ml', 'Balea Milch & Honig Maske, 16 ml',
 'ماسك الحليب والعسل من Balea', 'balea-milch-und-honig-maske',
 'Balea', (SELECT id FROM cats WHERE slug='skincare'), 'Face Mask',
 85, 0.45, 0, '[]'::jsonb,
 'ماسك غني بالحليب وعسل الأكاسيا يمنح البشرة إحساسًا بالنعومة والراحة.',
 ARRAY['مع Milch وAkazienhonig','مع Macadamia oil','عناية مكثفة للبشرة','يمنح إحساسًا ناعمًا','مناسب للبشرة المجهدة'],
 'مناسب لكل أنواع البشرة، خصوصًا البشرة المجهدة أو الجافة نسبيًا.',
 'يوضع بسخاء على بشرة نظيفة مع تجنب العين والشفاه. يُترك 10–15 دقيقة. تُزال البقايا بمنديل تجميلي ولا يلزم شطفه. يستخدم 1–2 مرة أسبوعيًا.',
 ARRAY['Milk / Lac Powder','Acacia Honey / Mel','Macadamia Oil','Panthenol','Glycerin'],
 'حجم 16 ml / 2x8 ml. قوام Creme/Mousse.',
 'للاستخدام الخارجي فقط. لا يستخدم للأطفال.', true),

(13, 'Schaebens Aloe Vera Tuchmaske, 1 St', 'Schaebens Aloe Vera Tuchmaske, 1 St',
 'ماسك Aloe Vera القماشي من Schaebens', 'schaebens-aloe-vera-sheet-mask',
 'Schaebens', (SELECT id FROM cats WHERE slug='skincare'), 'Sheet Mask',
 275, 1.45, 0, '[]'::jsonb,
 'ماسك قماشي بالألوفيرا يساعد على ترطيب البشرة وإنعاشها ودعم مظهرها الحيوي.',
 ARRAY['مع Aloe Vera','يساعد على ترطيب مكثف','ينعش ويهدئ البشرة','مع Hyaluronic Acid','مناسب لكل أنواع البشرة'],
 'مناسب لكل أنواع البشرة، خصوصًا البشرة المتعبة أو التي تحتاج إلى ترطيب وانتعاش.',
 'يوضع الماسك على بشرة نظيفة ويُضبط على ملامح الوجه. يُترك 10–15 دقيقة ثم يُزال. تُدلك البقايا أو تُزال بمنديل تجميلي. يستخدم 2–3 مرات أسبوعيًا.',
 ARRAY['Aloe Vera','Sodium Hyaluronate','Allantoin','Niacinamide','Glycerin'],
 'ماسك قماشي للاستخدام الواحد. يمكن حفظه في الثلاجة قبل الاستخدام لانتعاش إضافي.',
 'للاستخدام الخارجي فقط. أوقف الاستخدام عند حدوث تهيج.', true),

(14, 'Langhaarmädchen Haaröl Intense Repair, 150 ml', 'Langhaarmädchen Haaröl Intense Repair, 150 ml',
 'زيت شعر Intense Repair من Langhaar Mädchen', 'langhaar-maedchen-haaroel-intense-repair',
 'Langhaar Mädchen', (SELECT id FROM cats WHERE slug='hair-care'), 'Hair Oil',
 935, 4.95, 0, '[]'::jsonb,
 'زيت شعر غني بزيت جوز الهند وزيت البوريتي للعناية بالشعر المجهد وتقليل الهيشان.',
 ARRAY['مع Kokosöl وBuritiöl','Anti-Frizz Effect','عناية مكثفة بدون إثقال','حماية حرارية حتى 230°C','يساعد على سهولة التمشيط واللمعان'],
 'مناسب للشعر العادي، الجاف، الباهت، والمجهد.',
 'ضعي 2–3 ضغطات على اليدين ثم وزعيها على الأطوال والأطراف. يمكن استخدامه على شعر رطب أو جاف.',
 ARRAY['Coconut Oil','Buriti Oil','Sunflower Seed Oil','Vitamin E derivative'],
 'حجم 150 ml. Vegan، بدون Sulfate.',
 'لا تستخدمي كمية كبيرة حتى لا يثقل الشعر. تجنب العينين.', true),

(15, 'Balea Professional Haarkur Keratin Repair, 300 ml', 'Balea Professional Haarkur Keratin Repair, 300 ml',
 'ماسك/كريم Keratin Repair Haarkur من Balea Professional', 'balea-professional-keratin-repair-haarkur',
 'Balea Professional', (SELECT id FROM cats WHERE slug='hair-care'), 'Hair Treatment',
 520, 2.75, 0, '[]'::jsonb,
 'علاج شعر بالكيراتين والبيبتيدات للشعر الضعيف والمتضرر بنيويًا.',
 ARRAY['مع Keratin وPeptides','للشعر الضعيف والمتضرر','Pro-Strength Technology','بدون سيليكون','يساعد على مظهر شعر صحي ولامع'],
 'مناسب للشعر المتقصف، الضعيف، والمتضرر.',
 'يستخدم 1–2 مرة أسبوعيًا. يوزع بلطف على الأطوال والأطراف الرطبة، يُترك 2–3 دقائق ثم يُشطف جيدًا.',
 ARRAY['Hydrolyzed Keratin','Hydrolyzed Wheat Protein','Hydrolyzed Soy Protein','Hydrolyzed Corn Protein','Panthenol','Glycerin'],
 'حجم 300 ml. بدون Silicone وبدون Sulfate وبدون Alcohol حسب بيانات المنتج.',
 'يُشطف جيدًا. تجنب العينين.', true),

(16, 'Balea Glow & Care Finishing Spray, 150 ml', 'Balea Glow & Care Finishing Spray, 150 ml',
 'سبراي Glow & Care Finishing من Balea', 'balea-glow-and-care-finishing-spray',
 'Balea', (SELECT id FROM cats WHERE slug='hair-care'), 'Hair Styling',
 465, 2.45, 0, '[]'::jsonb,
 'سبراي نهائي للشعر يمنح مظهرًا لامعًا وملمسًا حريريًا مع Anti-Frizz Effect.',
 ARRAY['Finishing Spray','Anti-Frizz Effect','مع Camelina Oil','يترك إحساسًا حريريًا','يساعد على لمعان الشعر بعد التصفيف'],
 'مناسب كخطوة نهائية بعد التصفيف للشعر الذي يحتاج لمعانًا وتقليل الهيشان.',
 'بعد التصفيف، يُرش على الشعر الجاف من مسافة حوالي 30 cm بالتساوي.',
 ARRAY['Camelina Sativa Seed Oil','Isododecane','Triheptanoin','Acrylates Copolymer'],
 'حجم 150 ml. Aerosol finishing spray.',
 'منتج Aerosol قابل للاشتعال. يُحفظ بعيدًا عن الحرارة واللهب. لا يُثقب أو يُحرق حتى بعد الاستخدام. لا يُرش على لهب أو مصدر اشتعال. يُحفظ بعيدًا عن الأطفال.', true),

(17, 'Balea Hautrein 3in1 Reinigung, Peeling & Maske, 150 ml', 'Balea Hautrein 3in1 Reinigung, Peeling & Maske, 150 ml',
 'غسول + مقشر + ماسك 3 في 1 Hautrein من Balea', 'balea-hautrein-3in1-cleanser-peeling-mask',
 'Balea', (SELECT id FROM cats WHERE slug='skincare'), 'Face Cleanser',
 370, 1.95, 0, '[]'::jsonb,
 'منتج 3 في 1 للبشرة المعرضة للحبوب: غسول، مقشر، وماسك في نفس العبوة.',
 ARRAY['3 in 1: Cleanser + Peeling + Mask','مع Rosa Tonerde','مع Salicylic Acid وZinc','يساعد ضد الحبوب والرؤوس السوداء','تنظيف عميق للمسام','Vegan'],
 'مناسب للبشرة غير النقية والمعرضة للحبوب والرؤوس السوداء.',
 'كغسول: كمية بحجم حبة بندق مع قليل من الماء وتُغسل جيدًا. كمقشر: يوضع على بشرة رطبة ويدلك بحركات دائرية ثم يُشطف. كماسك: يوضع على بشرة جافة 2–3 مرات أسبوعيًا لمدة 3–5 دقائق ثم يُشطف جيدًا.',
 ARRAY['Kaolin','Pink clay / Rosa Tonerde','Salicylic Acid','Zinc PCA','Glycerin'],
 'حجم 150 ml. منتج Peeling/Cleanser/Mask. Vegan وبدون Parabens وبدون Mineral oils.',
 'تجنب منطقة العين والشفاه. لا تستخدم المقشر بعنف على البشرة الحساسة أو الملتهبة.', true),

(18, 'Balea Peel-Off Maske mit Aktivkohle, 100 ml', 'Balea Peel-Off Maske mit Aktivkohle, 100 ml',
 'ماسك Peel-Off بالفحم النشط من Balea', 'balea-peel-off-mask-aktivkohle',
 'Balea', (SELECT id FROM cats WHERE slug='skincare'), 'Peel-Off Mask',
 560, 2.95, 0, '[]'::jsonb,
 'ماسك Peel-Off بالفحم النشط يساعد على تنظيف المسام وإزالة الشوائب من سطح البشرة.',
 ARRAY['مع Activated Charcoal','تنظيف عميق للمسام','يساعد على إزالة الجلد الميت والشوائب','مع Aloe Vera وPanthenol وVitamin E','Vegan'],
 'مناسب للبشرة العادية والمختلطة. غير مناسب للبشرة شديدة الحساسية أو المتهيجة.',
 'يُرج جيدًا قبل الاستخدام. يوضع بعد تنظيف الوجه بطبقة متساوية مع تجنب العين والشفاه. يُترك 10–15 دقيقة حتى يجف، ثم يُسحب من الأطراف باتجاه المنتصف. تُشطف البقايا بالماء الفاتر. يمكن استخدامه حتى 3 مرات أسبوعيًا.',
 ARRAY['Charcoal Powder','Panthenol','Aloe Vera Extract','Vitamin E derivative','Glycerin'],
 'حجم 100 ml. Peel-Off mask بتركيبة Vegan.',
 'قد يسبب شدًا أثناء الإزالة. تجنب الحواجب وخط الشعر والجلد الحساس أو الملتهب. قد يسبب بقعًا على الملابس.', true),

(19, 'Balea Nosestrips mit Aktivkohle, 3 St', 'Balea Nosestrips mit Aktivkohle, 3 St',
 'شرائط الأنف بالفحم النشط من Balea', 'balea-nose-strips-aktivkohle',
 'Balea', (SELECT id FROM cats WHERE slug='skincare'), 'Nose Strips',
 330, 1.75, 0, '[]'::jsonb,
 'شرائط للأنف بالفحم النشط تساعد على إزالة الشوائب والرؤوس السوداء من منطقة الأنف.',
 ARRAY['مع Activated Charcoal','مع Glycolic Acid وTea Tree Oil','للأنف ضد الشوائب والرؤوس السوداء','مناسبة أيضًا للذقن والجبهة','Vegan'],
 'مناسب للبشرة العادية والمختلطة، خصوصًا منطقة الأنف المعرضة للرؤوس السوداء.',
 'بعد تنظيف البشرة، تُبلل منطقة الأنف أو الذقن أو الجبهة. يُوضع الشريط بأيدٍ نظيفة وجافة ويُضغط بلطف. يُترك 10–15 دقيقة ثم يُنزع ببطء من الجانب. تُشطف البقايا بالماء الفاتر.',
 ARRAY['VP/VA Copolymer','Bentonite','Charcoal Powder','Glycolic Acid','Tea Tree Oil','Glycerin'],
 'عبوة 3 شرائط. بدون Parfum وبدون Alcohol وبدون Mineral oils حسب بيانات المنتج.',
 'لا يستخدم على بشرة متهيجة أو بها حبوب ملتهبة أو حروق شمس. اترك على الأقل 3 أيام بين كل استخدام. الشريط للاستخدام مرة واحدة فقط.', true);
